version: '3.1'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local_db
    ports:
      - 5433:5432
    volumes:
      - local_db_data:/var/lib/postgresql/data
    networks:
      - db_net
volumes:
  local_db_data:
networks:
  db_net:
